[profile.default]
solc_version        = "0.8.22"
src                 = "src"
out                 = "out"
libs                = ["lib"]
optimizer           = true
optimizer_runs      = 200
via_ir              = true

# Push Chain Testnet configuration
[rpc_endpoints]
push_testnet        = "https://evm.rpc-testnet-donut-node1.push.org/"
push_testnet_alt    = "https://evm.rpc-testnet-donut-node2.push.org/"

# BlockScout explorer configuration for contract verification
[etherscan]
push_testnet        = { key = "blockscout", url = "https://donut.push.network/api", chain = 42101 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
